# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(312, 570)
        MainWindow.setStyleSheet("background-color: rgb(202, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 51, 31))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 190, 141, 31))
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 300, 161, 31))
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.doimk_btn = QtWidgets.QPushButton(self.centralwidget)
        self.doimk_btn.setGeometry(QtCore.QRect(80, 390, 151, 61))
        self.doimk_btn.setStyleSheet("background-color: rgb(125, 255, 147);")
        self.doimk_btn.setObjectName("doimk_btn")
        self.idmay_text = QtWidgets.QLineEdit(self.centralwidget)
        self.idmay_text.setEnabled(False)
        self.idmay_text.setGeometry(QtCore.QRect(40, 40, 241, 41))
        self.idmay_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.idmay_text.setObjectName("idmay_text")
        self.user_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.user_txt.setEnabled(False)
        self.user_txt.setGeometry(QtCore.QRect(40, 240, 241, 41))
        self.user_txt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.user_txt.setObjectName("user_txt")
        self.timeleft_text = QtWidgets.QLineEdit(self.centralwidget)
        self.timeleft_text.setEnabled(False)
        self.timeleft_text.setGeometry(QtCore.QRect(40, 340, 241, 41))
        self.timeleft_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.timeleft_text.setObjectName("timeleft_text")
        self.logout_btn = QtWidgets.QPushButton(self.centralwidget)
        self.logout_btn.setGeometry(QtCore.QRect(80, 470, 151, 61))
        self.logout_btn.setStyleSheet("background-color: rgb(255, 46, 46);")
        self.logout_btn.setObjectName("logout_btn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 90, 141, 31))
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.idkh_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.idkh_txt.setEnabled(False)
        self.idkh_txt.setGeometry(QtCore.QRect(40, 140, 241, 41))
        self.idkh_txt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.idkh_txt.setObjectName("idkh_txt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "❤️"))
        self.label.setText(_translate("MainWindow", "Máy :"))
        self.label_2.setText(_translate("MainWindow", "Tài khoản :"))
        self.label_3.setText(_translate("MainWindow", "Thời gian còn lại :"))
        self.doimk_btn.setText(_translate("MainWindow", "Đổi mật khẩu"))
        self.logout_btn.setText(_translate("MainWindow", "Đăng xuất"))
        self.label_4.setText(_translate("MainWindow", "Id :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
